### ISSUE TITLE
tx API call on Omnichest.info?

### ISSUE THREAD

**Issue by SterL** [OmniLayer/OmniJ#103]
I'm not sure what repository to post this in as I cant find the Omnichest.info repo. I need help. I would like to use the Omnichest.info API to get the number of confirmations on a given tx. I can see all the raw data from the /lookuptx.aspx?txid={txHash} but how do I get this same raw JSON data from an API call? I would prefer to not scrape your html for that raw data.

**Comment by msgilligan** [comment]
As far as I know, OmniChest.info is not Open Source.

I would recommend using the Feedback form the OmniChest.info site:
http://omnichest.info/reportbug.aspx

**Comment by SterL** [comment]
Thanks for the reply @msgilligan - I've used the Feedback form a number of different times but I have no way of knowing whether my requests will ever be met. All i need from Omnichest, is an API call that returns the raw data of a tx, given the coin and the txID of the tx. The current Omnichest API doc does not support this call but I assume it is written as all the raw data is displayed in HTML on the lookuptx page of a transaction.

**Comment by dexX7** [comment]
Hey @SterL,

let's ping @zathras-crypto from omnichest.info for more information. Maybe you could quickly describe what you intend to do?

**Comment by msgilligan** [comment]
@SterL OmniJ is definitely the wrong forum for discussion of OmniChest, but I don't mind if the discussion continues on this *closed* issue.

**Comment by msgilligan** [comment]
@dexX7 @zathras-crypto Where can we send @SterL other than the feedback form on OmniChest.info?

**Comment by dexX7** [comment]
How about creating a new repo, which acts as issue tracker for omnichest.info? Might be a bit over the top, but given that omnichest.info is the "go to" transaction explorer for the Omni Layer, it's not too far fetched in my opinion, and this case here shows that there is demand for.

At the very moment there is only the feedback form though.

Regarding the initial issue: I'm sure @zathras-crypto will report back, when he is available.

**Comment by SterL** [comment]
@dexX7 @msgilligan Thank you for the quick responses, support, and redirection! I'm happy to move this issue elsewhere if need be.

@zathras-crypto I can give you some more information as to why I need this data to help expedite this request. If the request is infeasible, I also understand =) I work for www.shapeshift.io and we are beginning work on some cool multisig functionality for our service. We need to be able to relay the number of confirmations on any given tx from 3rd party block explorers to validate a transaction. And since Omnichest.info is the official, go-to explorer for Omni assets, it would be best to grab our data from there. Not to mention, that Omnichest is the only explorer I can find with Omni assets =)

Please let me know if this call already exists, and I'm just blind/incapable. Or if my request to add this call is feasible or not for you to do.

**Comment by zathras-crypto** [comment]
@SterL apologies for the delayed response, it's been a crazy few days.  

First of all, there is a raw transaction API on OmniChest.info yep, I don't publish the details yet on the site API page as it already gets smashed with tens of thousands of requests a day and I'm in the process of rearchitecting it as multi-node to handle things a bit better.

All you need to do is push in a txid to the following link to pull the raw JSON data for a transaction:
http://omnichest.info/requeststat.aspx?stat=gettx&txid=
Example:
http://omnichest.info/requeststat.aspx?stat=gettx&txid=0f9a21eda30cd3e64d9ab8d9cfd33a2828d073ad41539dc60e649d9f39b92864

Now sadly there is one pretty significant caveat, especially since you're looking at confirmations.  

A little background; the current architecture for OmniChest uses an engine to query an OmniCore instance and populate a database which the front end web UI then queries.  The raw JSON returned for a transaction is stored in this database as part of querying OmniCore and provided in the API or via the 'Raw Data' section of a transaction lookup.  

The problem lies in that after 6 confirmations a transaction is considered confirmed and OmniChest no longer queries OmniCore for that transaction.  So this means the raw JSON field in the database no longer gets updated after 6 confirmations, and thus the confirmations field therein goes out-of-date (stays stuck at 6 or 7 confirmations).

I'm working on a new version of OmniChest at the moment, and this is one of the things I'm working on addressing, FYI.

Also, not to try and discourage any usage of OmniChest, but I always recommend an OmniCore node where it's feasible.  The reference client is the safest way to query data without having to trust a 3rd party :)  I understand it's not always feasible to run your own node (which is why I make the API available on OmniChest) but I always try to point to OmniCore for new users of the API just in case they haven't considered that avenue.

If you're definitely going the API route, perhaps some redundancy (in both availability and data verification) could be achieved by querying OmniWallet also - paging @achamely to advise on whether OmniWallet can be queried for transactions in such a way.

> How about creating a new repo, which acts as issue tracker for omnichest.info?

Sure, I can do that.  I'll pipe in feedback requests into issues (I like to maintain a feedback form because then people don't necessarily need a github account).

Thanks guys
Z

**Comment by zathras-crypto** [comment]
@dexX7 https://github.com/zathras-crypto/omnichest.info

**Comment by SterL** [comment]
@zathras-crypto Perfect! Thank you, sir. I think the 6 Confirmations will work at least for now. The 'checkvalid' call you have should be sufficient enough for what we are doing, but I'm going a bit Above & Beyond to try and match the data in the API, I'm writing. And we wont be smashing your API with requests; just a few per day most likely :) Quick question though: how hard would it be to add the blocknumber field to that gettx call and then add a currentheight call? Then I could simply just call both of those and do currentheight - blocknumber to get the actual number of confirmations on that tx.

On the note of running the OmniCore node, this was my next option since Omnichest seems to be the only explorer available for Omni Assets. The only problem with this option is that ShapeShift will still need a 3rd party organization to own and operate the software. The idea is that ShapeShift will be unaffiliated with this 3rd party so that the 3rd party can act as a sort of middleman for multisig transactions.

**Comment by zathras-crypto** [comment]
> Quick question though: how hard would it be to add the blocknumber field to that gettx call and then add a currentheight call?

The data is passthrough from Omni Core (to ensure Omni Chest stays true to reference data).  So the 'block' attribute needs to be added to the Omni Core ```omni_gettransaction``` response.  Thankfully @dexX7 has already done this in 0.0.10 :)  The next version of Omni Chest uses 0.0.10 so inherits the addition of the 'block' attribute to the API data.

I'm working on a fix for the confirmations attribute anyway for the next version so a workaround shouldn't be needed once that's sorted.  In the interim until OmniChest v6 goes live I've added a couple of APIs for you which should serve as a workaround.

To directly request the block a transaction was mined in (example tx, replace txid as needed):
http://omnichest.info/requeststat.aspx?stat=customapireq_gettxblock&txid=0f9a21eda30cd3e64d9ab8d9cfd33a2828d073ad41539dc60e649d9f39b92864

To request the last block OmniChest processed:
http://omnichest.info/requeststat.aspx?stat=customapireq_lastblockprocessed

To have OmniChest do the calculation ```(last_block_processed - transaction_block) + 1```:
http://omnichest.info/requeststat.aspx?stat=customapireq_gettxconfirmations&txid=0f9a21eda30cd3e64d9ab8d9cfd33a2828d073ad41539dc60e649d9f39b92864

It's good that you're using the checkvalid API too as using the Bitcoin network as a transport means Omni transactions can still be 'confirmed' but be state-invalid (eg insufficient balance etc).

Hope that helps, let me know if I can assist further :)

Thanks
Z

**Comment by SterL** [comment]
AhHA this is perfect! Thank you so much for the help @zathras-crypto @dexX7 @msgilligan
