### ISSUE TITLE
Field "frozen" added to balance results

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#148]
A new field "frozen" is always shown in Omni Core v0.3.1, when retrieving balances (e.g. with `omni_getbalance`). So far, this field was only shown, when there were actually frozen tokens.

This causes the following error:

```
2018-08-08 11:24:25.536 SEVERE  [org.consensusj.jsonrpc.RpcClient] (org.consensusj.jsonrpc.RpcClient sendRequestForResponse) JsonProcessingException: {} 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "frozen" (class foundation.omni.rpc.BalanceEntry), not marked as ignorable (2 known properties: "reserved", "balance"])
```

**Comment by msgilligan** [comment]
This should be a pretty easy fix.

**Comment by msgilligan** [comment]
@dexX7 , either I spoke too soon or there's a separate issue.

I thought this commit would fix it:
 d7dab175e09e0d1021e0c7279b1a3385cedc4478

But one test is still failing: 
[`foundation.omni.test.rpc.basic.GetBalancesSpec.omniGetAllBalancesForAddress returns correct balances`](https://ci.omni.foundation/job/omni-integ-regtest/lastCompletedBuild/testReport/foundation.omni.test.rpc.basic/GetBalancesSpec/omniGetAllBalancesForAddress_returns_correct_balances/)
because `omniGetAllBalancesForAddress` returns an empty `Map`.

I made one additional cleanup commit (partly to make it easier to file compare some classes):
c9c5d857430f8502672e87e8375acce99418ba63

But without doing more thorough debugging and tracing I can't see what the problem is. Any ideas @dexX7 ?

**Comment by dexX7** [comment]
Argh, I'm very sorry, but it wasn't your fault, but mine. When also adding a "name" field to omni_getallbalancesforaddress, I accidently swapped a statement, resulting in skipping to add balances at all. It's now fixed via https://github.com/OmniLayer/omnicore/pull/727/files#diff-b0f1af5398e07013a5575d40f747a870L875.

That's very good! Your fix works. Could a "name" field be added to omni_getallbalancesforaddress in a similar fashion? That's the other change I made in the last days.

**Comment by msgilligan** [comment]
@dexX7 Can we close this issue now?

**Comment by dexX7** [comment]
Yup, resolved. Thank you a lot!
