### ISSUE TITLE
how to generate a transaction and broadcast it?

### ISSUE THREAD

**Issue by lizaiqian** [OmniLayer/OmniJ#154]
Sorry, I can't find any samples to use Omnij. broadcast by Peer of bitcoinj or others? I'm new, and I'm learning how to complete the basic function such as getBalance, sendTransaction in Java.

**Comment by msgilligan** [comment]
You can create a **bitcionj** `Transaction` using `foundation.omni.tx.OmniTxBuilder`. You can broadcast the transaction with a bitcoinj peer or using an Omni Core RPC connection. For an example of how to do it, you can look at our [OmniTxBuilderIntegSpec test](https://github.com/OmniLayer/OmniJ/blob/master/omnij-rpc/src/integ/groovy/foundation/omni/test/tx/OmniTxBuilderIntegSpec.groovy#L46-L70). (The test is written in Groovy using the Spock test framework, but is close enough to Java to be useful to you, I hope. It is also running using an RPC connection to Omni Core in Regression Test mode -- thus the use of `generate()` to make a block.)

**Comment by msgilligan** [comment]
To get the balance for an Omni token on a Bitcoin address, you can either use an RPC connection to Omni Core or a REST connection to Omniwallet.

For RPC and Omni Core use `OmniClient.omniGetBalance()`.
For a REST connection to Omniwallet use `OmniwalletClient.balancesForAddress()`

**Comment by msgilligan** [comment]
@alikopasa `listUnspentJ` is a method of `OmniClient` (in the Spock integration tests, methods of `OmniClient` can be called directly -- because `BaseRegTestSpec` implements `OmniTestClientDelegate`)

`listUnspentJ`  is inherited from and implemented in `BitcoinExtendedClient` in **ConsensusJ** See: https://github.com/ConsensusJ/consensusj/blob/master/cj-btc-jsonrpc/src/main/java/com/msgilligan/bitcoinj/rpc/BitcoinExtendedClient.java#L250-L265

Depending upon the application you are implementing you may want to get your UTXOs elsewhere. But, in order to use `omniTxBuilder.createSignedSimpleSend()` you must pass it a valid list of **bitcoinj** `TransactionOutput` objects.

**Comment by sj225** [comment]
Hi,
OmniClient use rpc. I want use only bitcoinj dns seeds i.e don't want to setup local node.
Please suggest alternate way to send USDT transaction using bitcoinj peers.

**Comment by msgilligan** [comment]
@sj225 Use **bitcoinj** peers to collect Bitcoin UTXO information and use it to build an Omni transaction (inside a bitcoinj transaction) using `OmniTxBuilder`, then send the Transaction using bitcoinj.

**Comment by parcool** [comment]
I just sign it and broadcast it by rpc api,but I saw the sourcecode to get `listUnspentJ ` needs provide a `listUnspentJ ` object what it need `server`,`rpcuser`,`rpcpassword`... what is it?I just want sign it offline.
