### ISSUE TITLE
how to consolidate all address balance to one wallet and send from that wallet only?

### ISSUE THREAD

**Issue by Abhishekoodles1** [OmniLayer/OmniJ#160]
I have made the different address of wallet and deposited Omni to it.  Now when I use `./omnicore-cli omni_getwalletaddressbalances`  it showing all balance associated with each address which is fine. Now when I see `./omnicore-cli omni_getwalletbalances` it showing total balance of wallet which is also fine. As I  know we need some BTC in source address when we are sending Omni. What I want to send Omni from my wallet only or any single account.

I am thinking to create a new address of my wallet and put some BTC to it. And in case of transfer Omni I want to use this as from address, but now this address has not Omni.  What is the right approach to consolidate all balance in one place and use that account for the transaction as sender?

**Comment by msgilligan** [comment]
This is the *OmniJ* project -- Java libraries for Omni -- and is not the correct place to ask your question.

I'm not 100% sure I understand your question, but it sounds to me like you might want to put some BTC on your existing Omni address(es) -- you could also try consolidating everything on a single address if you like.

Since you're using Omni Core, you should try asking the questions over there: https://github.com/OmniLayer/Omnicore/issues
