### ISSUE TITLE
Improved calculation of transaction fees and output amounts

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/OmniJ#78]
Currently transaction fees and exodus/reference output amounts are hardcoded in `OmniTxBuilder`. These fees need to be dynamically and correctly calculated.

**Comment by dexX7** [comment]
I took a look at this, and BitcoinJ has [COIN getMinNonDustValue()](https://bitcoinj.github.io/javadoc/0.12.3/org/bitcoinj/core/TransactionOutput.html#getMinNonDustValue--) as well as [COIN getMinNonDustValue(Coin feePerKbRequired)](https://bitcoinj.github.io/javadoc/0.12.3/org/bitcoinj/core/TransactionOutput.html#getMinNonDustValue-org.bitcoinj.core.Coin-), which could be used in combination with [setValue(Coin value)](https://bitcoinj.github.io/javadoc/0.12.3/org/bitcoinj/core/TransactionOutput.html#setValue-org.bitcoinj.core.Coin-).

The transaction fee is more complicated, because you'd need to start with some fee, then sign the transaction, check, whether the fee is sufficient, and if not, attach a higher fee, then sign the transaction once more, check the fee, [...].

**Comment by msgilligan** [comment]
Thanks for this, Dexx.

**Comment by dexX7** [comment]
Alternatively, the dust limit could be calculated manually, as done in Omni Core, but BitcoinJ should come up with similar results.

**Comment by msgilligan** [comment]
Thanks @dexX7 - based upon your suggestions I committed c4d5071c05a451843a74034bb354996795bb4587 which should set the correct output amounts.

**Comment by msgilligan** [comment]
@dexX7 Check out there release notes for **bitcoinj** `v0.14.1`: https://bitcoinj.github.io/release-notes

Maybe we should use the Tx fee rate?

**Comment by msgilligan** [comment]
Since #125 we are using bitcoinj 0.14.1

**Comment by msgilligan** [comment]
@dexX7 I'm thinking if we just use the "fee rate" from **bitcoinj** 0.14.1 we can call this issue, resolved. This would use the Omni transaction size multiplied by the recommended bitcoinj fee rate. I don't think dynamic fees ala Bitcoin Core are feasible for this release. What are your thoughts?

**Comment by dexX7** [comment]
> This would use the Omni transaction size multiplied by the recommended bitcoinj fee rate.

Sounds like a great improvement to me!

**Comment by msgilligan** [comment]
Fixed in 6d24b1c497e467a7dd61f28d5f275992d81692b0 and released in 0.4.0
